name: 'jaffle_shop'

config-version: 2
version: '0.1'

profile: 'jaffle_shop'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analysis"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"
    - "logs"

require-dbt-version: [">=1.0.0", "<2.0.0"]

models:
  jaffle_shop:
      materialized: table
      staging:
        materialized: view

on-run-end:
    - "ALTER TABLE dbt_alice.customers ADD CONSTRAINT unique_customers UNIQUE (customer_id)"
    - "ALTER TABLE dbt_alice.orders ADD CONSTRAINT unique_orders UNIQUE (order_id)"
    - "ALTER TABLE dbt_alice.orders ADD CONSTRAINT fk_orders_customers FOREIGN KEY (customer_id) REFERENCES dbt_alice.customers (customer_id)"
    - "ALTER TABLE dbt_alice.payments ADD CONSTRAINT fk_payments_orders FOREIGN KEY (order_id) REFERENCES dbt_alice.orders (order_id)"